<?php

namespace App\Services;

/**
 * Service pour la gestion des quiz
 */
class QuizService
{
    public function getQuizQuestions($language)
    {
        $allQuestions = [
            'html5' => [
                ['question' => 'Que signifie HTML ?', 'options' => ['Hyper Text Markup Language', 'High Tech Modern Language', 'Home Tool Markup Language', 'Hyperlinks and Text Markup Language'], 'correct' => 0],
                ['question' => 'Quelle balise est utilisée pour créer un lien hypertexte ?', 'options' => ['<link>', '<a>', '<href>', '<url>'], 'correct' => 1],
                ['question' => 'Quelle balise définit le titre d\'une page HTML ?', 'options' => ['<head>', '<title>', '<meta>', '<header>'], 'correct' => 1],
                ['question' => 'Quelle balise est utilisée pour insérer une image ?', 'options' => ['<image>', '<img>', '<picture>', '<src>'], 'correct' => 1],
                ['question' => 'Quelle balise crée un paragraphe ?', 'options' => ['<para>', '<p>', '<paragraph>', '<text>'], 'correct' => 1],
                ['question' => 'Quelle balise crée une liste non ordonnée ?', 'options' => ['<ol>', '<ul>', '<list>', '<li>'], 'correct' => 1],
                ['question' => 'Quel attribut spécifie une URL alternative pour une image ?', 'options' => ['title', 'alt', 'src', 'href'], 'correct' => 1],
                ['question' => 'Quelle balise définit un tableau ?', 'options' => ['<table>', '<tab>', '<tr>', '<td>'], 'correct' => 0],
                ['question' => 'Quelle balise crée un titre de niveau 1 ?', 'options' => ['<heading>', '<h1>', '<title>', '<head>'], 'correct' => 1],
                ['question' => 'Quelle balise définit une ligne dans un tableau ?', 'options' => ['<td>', '<tr>', '<th>', '<table>'], 'correct' => 1],
                ['question' => 'Quel attribut ouvre un lien dans un nouvel onglet ?', 'options' => ['new', 'target="_blank"', 'open', 'window'], 'correct' => 1],
                ['question' => 'Quelle balise crée un formulaire ?', 'options' => ['<input>', '<form>', '<field>', '<submit>'], 'correct' => 1],
                ['question' => 'Quelle balise HTML5 définit une section ?', 'options' => ['<div>', '<section>', '<article>', '<part>'], 'correct' => 1],
                ['question' => 'Quelle balise crée un champ de saisie de texte ?', 'options' => ['<textbox>', '<input>', '<field>', '<text>'], 'correct' => 1],
                ['question' => 'Quelle balise définit un en-tête de page ?', 'options' => ['<head>', '<header>', '<top>', '<nav>'], 'correct' => 1],
                ['question' => 'Quelle balise crée une liste ordonnée ?', 'options' => ['<ul>', '<ol>', '<list>', '<order>'], 'correct' => 1],
                ['question' => 'Quel attribut définit l\'URL d\'un lien ?', 'options' => ['src', 'link', 'href', 'url'], 'correct' => 2],
                ['question' => 'Quelle balise définit un pied de page ?', 'options' => ['<bottom>', '<footer>', '<foot>', '<end>'], 'correct' => 1],
                ['question' => 'Quelle balise crée un bouton ?', 'options' => ['<btn>', '<button>', '<input type="button">', 'Les deux B et C'], 'correct' => 3],
                ['question' => 'Quelle balise HTML5 définit une navigation ?', 'options' => ['<navigate>', '<nav>', '<menu>', '<links>'], 'correct' => 1],
            ],
            'css3' => [
                ['question' => 'Que signifie CSS ?', 'options' => ['Cascading Style Sheets', 'Computer Style Sheets', 'Creative Style Sheets', 'Colorful Style Sheets'], 'correct' => 0],
                ['question' => 'Quelle propriété change la couleur du texte ?', 'options' => ['text-color', 'color', 'font-color', 'text-style'], 'correct' => 1],
                ['question' => 'Comment ajouter une couleur de fond ?', 'options' => ['color', 'background-color', 'bg-color', 'bgcolor'], 'correct' => 1],
                ['question' => 'Quelle propriété change la taille de la police ?', 'options' => ['text-size', 'font-size', 'text-style', 'font-weight'], 'correct' => 1],
                ['question' => 'Comment centrer un texte ?', 'options' => ['text-align: center', 'align: center', 'text: center', 'center: text'], 'correct' => 0],
                ['question' => 'Quelle propriété ajoute une bordure ?', 'options' => ['outline', 'border', 'edge', 'frame'], 'correct' => 1],
                ['question' => 'Comment rendre un élément invisible ?', 'options' => ['visibility: hidden', 'display: none', 'opacity: 0', 'Toutes les réponses'], 'correct' => 3],
                ['question' => 'Quelle propriété définit l\'espacement interne ?', 'options' => ['margin', 'padding', 'spacing', 'border'], 'correct' => 1],
                ['question' => 'Quelle propriété définit l\'espacement externe ?', 'options' => ['margin', 'padding', 'spacing', 'border'], 'correct' => 0],
                ['question' => 'Comment sélectionner une classe en CSS ?', 'options' => ['#classe', '.classe', '*classe', 'classe'], 'correct' => 1],
                ['question' => 'Comment sélectionner un ID en CSS ?', 'options' => ['#id', '.id', '*id', 'id'], 'correct' => 0],
                ['question' => 'Quelle propriété change la police ?', 'options' => ['font-family', 'font-type', 'font-style', 'text-font'], 'correct' => 0],
                ['question' => 'Comment mettre un texte en gras ?', 'options' => ['font-weight: bold', 'text-style: bold', 'font-bold', 'text-weight: bold'], 'correct' => 0],
                ['question' => 'Quelle propriété contrôle la largeur ?', 'options' => ['width', 'size', 'length', 'dimension'], 'correct' => 0],
                ['question' => 'Quelle propriété contrôle la hauteur ?', 'options' => ['height', 'size', 'length', 'dimension'], 'correct' => 0],
                ['question' => 'Comment créer une animation CSS ?', 'options' => ['@animation', '@keyframes', '@animate', '@motion'], 'correct' => 1],
                ['question' => 'Quelle propriété définit la position ?', 'options' => ['position', 'location', 'place', 'pos'], 'correct' => 0],
                ['question' => 'Quelle valeur de display crée un flexbox ?', 'options' => ['flex', 'flexbox', 'flexible', 'box'], 'correct' => 0],
                ['question' => 'Quelle valeur de display crée une grille ?', 'options' => ['grid', 'table', 'gridbox', 'layout'], 'correct' => 0],
                ['question' => 'Comment arrondir les coins ?', 'options' => ['corner-radius', 'border-radius', 'round-corner', 'border-round'], 'correct' => 1],
            ],
            'javascript' => [
                ['question' => 'Comment déclarer une variable en JavaScript ?', 'options' => ['var x', 'variable x', 'v x', 'dim x'], 'correct' => 0],
                ['question' => 'Quelle méthode affiche un message dans la console ?', 'options' => ['console.log()', 'print()', 'echo()', 'display()'], 'correct' => 0],
                ['question' => 'Comment créer une fonction ?', 'options' => ['function myFunc()', 'def myFunc()', 'func myFunc()', 'create myFunc()'], 'correct' => 0],
                ['question' => 'Quel opérateur teste l\'égalité stricte ?', 'options' => ['==', '===', '=', '!='], 'correct' => 1],
                ['question' => 'Comment ajouter un commentaire sur une ligne ?', 'options' => ['// commentaire', '/* commentaire */', '# commentaire', '-- commentaire'], 'correct' => 0],
                ['question' => 'Quelle méthode sélectionne un élément par ID ?', 'options' => ['getElementById()', 'getElement()', 'selectById()', 'findById()'], 'correct' => 0],
                ['question' => 'Comment créer un tableau ?', 'options' => ['var arr = []', 'var arr = ()', 'var arr = {}', 'var arr = <>'], 'correct' => 0],
                ['question' => 'Quelle méthode ajoute un élément à la fin d\'un tableau ?', 'options' => ['add()', 'push()', 'append()', 'insert()'], 'correct' => 1],
                ['question' => 'Comment créer une boucle for ?', 'options' => ['for (i = 0; i < 5; i++)', 'for i = 0 to 5', 'for (i in 5)', 'loop (i < 5)'], 'correct' => 0],
                ['question' => 'Quelle méthode convertit une chaîne en nombre ?', 'options' => ['parseInt()', 'toNumber()', 'convert()', 'number()'], 'correct' => 0],
                ['question' => 'Comment créer un objet ?', 'options' => ['var obj = []', 'var obj = ()', 'var obj = {}', 'var obj = <>'], 'correct' => 2],
                ['question' => 'Quelle méthode retourne la longueur d\'une chaîne ?', 'options' => ['length', 'size()', 'count()', 'len()'], 'correct' => 0],
                ['question' => 'Comment ajouter un événement click ?', 'options' => ['element.click()', 'element.addEventListener("click")', 'element.onClick()', 'element.addClick()'], 'correct' => 1],
                ['question' => 'Quel mot-clé définit une constante ?', 'options' => ['var', 'let', 'const', 'constant'], 'correct' => 2],
                ['question' => 'Comment arrondir un nombre ?', 'options' => ['Math.round()', 'round()', 'Math.ceil()', 'number.round()'], 'correct' => 0],
                ['question' => 'Quelle méthode génère un nombre aléatoire ?', 'options' => ['Math.random()', 'random()', 'Math.rand()', 'getRandom()'], 'correct' => 0],
                ['question' => 'Comment vérifier le type d\'une variable ?', 'options' => ['typeof', 'type()', 'getType()', 'varType()'], 'correct' => 0],
                ['question' => 'Quelle méthode supprime le dernier élément d\'un tableau ?', 'options' => ['remove()', 'pop()', 'delete()', 'removeLast()'], 'correct' => 1],
                ['question' => 'Comment créer une condition if ?', 'options' => ['if (x > 5)', 'if x > 5', 'if (x > 5) then', 'if x > 5 then'], 'correct' => 0],
                ['question' => 'Quelle méthode transforme un tableau en chaîne ?', 'options' => ['toString()', 'join()', 'concat()', 'Les deux A et B'], 'correct' => 3],
            ],
            'php' => [
                ['question' => 'Que signifie PHP ?', 'options' => ['Personal Home Page', 'PHP: Hypertext Preprocessor', 'Private Home Page', 'Public HTML Page'], 'correct' => 1],
                ['question' => 'Comment commence une variable en PHP ?', 'options' => ['@', '#', '$', '&'], 'correct' => 2],
                ['question' => 'Comment afficher du texte en PHP ?', 'options' => ['echo', 'print', 'display', 'Les deux A et B'], 'correct' => 3],
                ['question' => 'Comment créer un commentaire sur une ligne ?', 'options' => ['// commentaire', '# commentaire', '/* commentaire */', 'Les deux A et B'], 'correct' => 3],
                ['question' => 'Quelle fonction retourne la longueur d\'une chaîne ?', 'options' => ['strlen()', 'length()', 'size()', 'count()'], 'correct' => 0],
                ['question' => 'Comment créer un tableau en PHP ?', 'options' => ['array()', '[]', '$arr = []', 'Toutes les réponses'], 'correct' => 3],
                ['question' => 'Quelle superglobale contient les données POST ?', 'options' => ['$POST', '$_POST', '$FORM', '$_FORM'], 'correct' => 1],
                ['question' => 'Comment inclure un fichier PHP ?', 'options' => ['include', 'require', 'import', 'Les deux A et B'], 'correct' => 3],
                ['question' => 'Quelle fonction vérifie si une variable existe ?', 'options' => ['isset()', 'exists()', 'defined()', 'check()'], 'correct' => 0],
                ['question' => 'Comment créer une fonction ?', 'options' => ['function myFunc()', 'def myFunc()', 'func myFunc()', 'create myFunc()'], 'correct' => 0],
                ['question' => 'Quelle fonction connecte à MySQL ?', 'options' => ['mysql_connect()', 'mysqli_connect()', 'connect_mysql()', 'db_connect()'], 'correct' => 1],
                ['question' => 'Comment démarrer une session ?', 'options' => ['session_start()', 'start_session()', 'session_begin()', 'begin_session()'], 'correct' => 0],
                ['question' => 'Quelle superglobale contient les cookies ?', 'options' => ['$COOKIE', '$_COOKIE', '$COOKIES', '$_COOKIES'], 'correct' => 1],
                ['question' => 'Comment rediriger vers une autre page ?', 'options' => ['header("Location: page.php")', 'redirect("page.php")', 'goto("page.php")', 'location("page.php")'], 'correct' => 0],
                ['question' => 'Quelle fonction retourne le type d\'une variable ?', 'options' => ['gettype()', 'typeof()', 'type()', 'vartype()'], 'correct' => 0],
                ['question' => 'Comment créer une classe ?', 'options' => ['class MyClass {}', 'create class MyClass', 'new class MyClass', 'define class MyClass'], 'correct' => 0],
                ['question' => 'Quelle fonction compte les éléments d\'un tableau ?', 'options' => ['count()', 'length()', 'size()', 'sizeof()'], 'correct' => 0],
                ['question' => 'Comment vérifier si un fichier existe ?', 'options' => ['file_exists()', 'exists()', 'is_file()', 'check_file()'], 'correct' => 0],
                ['question' => 'Quelle fonction convertit en entier ?', 'options' => ['intval()', 'int()', 'toInt()', 'parseInt()'], 'correct' => 0],
                ['question' => 'Comment créer une constante ?', 'options' => ['define("NAME", "value")', 'const NAME = "value"', 'constant NAME = "value"', 'Les deux A et B'], 'correct' => 3],
            ],
            'bootstrap' => [
                ['question' => 'Que signifie Bootstrap ?', 'options' => ['Un framework CSS', 'Un langage de programmation', 'Une base de données', 'Un serveur web'], 'correct' => 0],
                ['question' => 'Quelle classe crée un conteneur responsive ?', 'options' => ['.container', '.responsive', '.wrapper', '.box'], 'correct' => 0],
                ['question' => 'Quelle classe crée une ligne dans la grille ?', 'options' => ['.line', '.row', '.grid', '.flex'], 'correct' => 1],
                ['question' => 'Quelle classe crée une colonne ?', 'options' => ['.column', '.col', '.grid-col', '.cell'], 'correct' => 1],
                ['question' => 'Quelle classe crée un bouton primaire ?', 'options' => ['.btn-primary', '.button-primary', '.primary-btn', '.btn-blue'], 'correct' => 0],
                ['question' => 'Quelle classe centre le texte ?', 'options' => ['.center', '.text-center', '.align-center', '.middle'], 'correct' => 1],
                ['question' => 'Quelle classe crée une alerte ?', 'options' => ['.alert', '.message', '.notification', '.warning'], 'correct' => 0],
                ['question' => 'Quelle classe crée une navbar ?', 'options' => ['.navigation', '.navbar', '.nav', '.menu'], 'correct' => 1],
                ['question' => 'Quelle classe crée une card ?', 'options' => ['.card', '.box', '.panel', '.container'], 'correct' => 0],
                ['question' => 'Quelle classe ajoute une marge en haut ?', 'options' => ['.margin-top', '.mt-3', '.top-margin', '.m-top'], 'correct' => 1],
                ['question' => 'Quelle classe crée un badge ?', 'options' => ['.badge', '.label', '.tag', '.chip'], 'correct' => 0],
                ['question' => 'Quelle classe crée une modal ?', 'options' => ['.modal', '.popup', '.dialog', '.window'], 'correct' => 0],
                ['question' => 'Quelle classe masque un élément sur mobile ?', 'options' => ['.hide-mobile', '.d-none d-md-block', '.mobile-hide', '.hidden-xs'], 'correct' => 1],
                ['question' => 'Quelle classe crée un tableau rayé ?', 'options' => ['.table-striped', '.striped-table', '.table-zebra', '.zebra'], 'correct' => 0],
                ['question' => 'Quelle classe crée un formulaire inline ?', 'options' => ['.form-inline', '.inline-form', '.form-horizontal', '.horizontal'], 'correct' => 0],
            ],
            'git' => [
                ['question' => 'Que signifie Git ?', 'options' => ['Global Information Tracker', 'Un système de contrôle de version', 'Un langage de programmation', 'Un éditeur de code'], 'correct' => 1],
                ['question' => 'Quelle commande initialise un dépôt Git ?', 'options' => ['git start', 'git init', 'git create', 'git new'], 'correct' => 1],
                ['question' => 'Quelle commande ajoute tous les fichiers ?', 'options' => ['git add *', 'git add .', 'git add all', 'git add --all'], 'correct' => 1],
                ['question' => 'Quelle commande crée un commit ?', 'options' => ['git commit', 'git save', 'git push', 'git create'], 'correct' => 0],
                ['question' => 'Quelle commande envoie vers le dépôt distant ?', 'options' => ['git send', 'git upload', 'git push', 'git commit'], 'correct' => 2],
                ['question' => 'Quelle commande récupère les changements ?', 'options' => ['git get', 'git fetch', 'git pull', 'git download'], 'correct' => 2],
                ['question' => 'Quelle commande crée une branche ?', 'options' => ['git branch nom', 'git create nom', 'git new nom', 'git add nom'], 'correct' => 0],
                ['question' => 'Quelle commande change de branche ?', 'options' => ['git change', 'git switch', 'git checkout', 'Les deux B et C'], 'correct' => 3],
                ['question' => 'Quelle commande fusionne des branches ?', 'options' => ['git merge', 'git combine', 'git join', 'git fusion'], 'correct' => 0],
                ['question' => 'Quelle commande affiche l\'historique ?', 'options' => ['git history', 'git log', 'git show', 'git list'], 'correct' => 1],
                ['question' => 'Quelle commande affiche le statut ?', 'options' => ['git status', 'git state', 'git info', 'git check'], 'correct' => 0],
                ['question' => 'Quelle commande clone un dépôt ?', 'options' => ['git copy', 'git clone', 'git download', 'git get'], 'correct' => 1],
                ['question' => 'Quelle commande annule les modifications ?', 'options' => ['git undo', 'git reset', 'git revert', 'git cancel'], 'correct' => 1],
                ['question' => 'Quelle commande affiche les différences ?', 'options' => ['git diff', 'git compare', 'git changes', 'git show'], 'correct' => 0],
                ['question' => 'Quelle commande configure le nom d\'utilisateur ?', 'options' => ['git config user.name', 'git set name', 'git user name', 'git name'], 'correct' => 0],
            ],
            'wordpress' => [
                ['question' => 'Que signifie WordPress ?', 'options' => ['Un CMS', 'Un langage de programmation', 'Une base de données', 'Un serveur'], 'correct' => 0],
                ['question' => 'Quelle fonction affiche le titre ?', 'options' => ['get_title()', 'the_title()', 'show_title()', 'title()'], 'correct' => 1],
                ['question' => 'Quelle fonction affiche le contenu ?', 'options' => ['get_content()', 'the_content()', 'show_content()', 'content()'], 'correct' => 1],
                ['question' => 'Quelle boucle affiche les articles ?', 'options' => ['The Loop', 'Post Loop', 'Article Loop', 'Content Loop'], 'correct' => 0],
                ['question' => 'Quelle fonction vérifie s\'il y a des articles ?', 'options' => ['has_posts()', 'have_posts()', 'check_posts()', 'posts_exist()'], 'correct' => 1],
                ['question' => 'Quelle fonction affiche l\'image à la une ?', 'options' => ['the_thumbnail()', 'the_post_thumbnail()', 'featured_image()', 'post_image()'], 'correct' => 1],
                ['question' => 'Quelle fonction affiche le menu ?', 'options' => ['wp_menu()', 'wp_nav_menu()', 'the_menu()', 'show_menu()'], 'correct' => 1],
                ['question' => 'Quel fichier contient les fonctions du thème ?', 'options' => ['functions.php', 'theme.php', 'config.php', 'setup.php'], 'correct' => 0],
                ['question' => 'Quel fichier est le template principal ?', 'options' => ['main.php', 'index.php', 'home.php', 'template.php'], 'correct' => 1],
                ['question' => 'Quelle fonction enregistre un menu ?', 'options' => ['register_menu()', 'register_nav_menu()', 'add_menu()', 'create_menu()'], 'correct' => 1],
                ['question' => 'Quelle fonction enregistre un widget ?', 'options' => ['register_widget()', 'register_sidebar()', 'add_widget()', 'create_widget()'], 'correct' => 1],
                ['question' => 'Quelle fonction affiche le footer ?', 'options' => ['wp_footer()', 'get_footer()', 'the_footer()', 'show_footer()'], 'correct' => 0],
                ['question' => 'Quelle fonction affiche le header ?', 'options' => ['wp_header()', 'get_header()', 'the_header()', 'show_header()'], 'correct' => 1],
                ['question' => 'Quelle fonction récupère une option ?', 'options' => ['get_option()', 'option()', 'wp_option()', 'the_option()'], 'correct' => 0],
                ['question' => 'Quelle fonction crée un custom post type ?', 'options' => ['create_post_type()', 'register_post_type()', 'add_post_type()', 'new_post_type()'], 'correct' => 1],
            ],
            'ia' => [
                ['question' => 'Que signifie IA ?', 'options' => ['Intelligence Artificielle', 'Information Automatique', 'Internet Avancé', 'Interface Automatisée'], 'correct' => 0],
                ['question' => 'Que signifie ML ?', 'options' => ['Machine Learning', 'Modern Language', 'Multiple Layers', 'Memory Learning'], 'correct' => 0],
                ['question' => 'Quel type d\'apprentissage utilise des données étiquetées ?', 'options' => ['Non supervisé', 'Supervisé', 'Par renforcement', 'Semi-supervisé'], 'correct' => 1],
                ['question' => 'Quelle bibliothèque Python est populaire pour l\'IA ?', 'options' => ['TensorFlow', 'Django', 'Flask', 'Pandas'], 'correct' => 0],
                ['question' => 'Qu\'est-ce qu\'un neurone artificiel ?', 'options' => ['Une unité de calcul', 'Un algorithme', 'Un langage', 'Un framework'], 'correct' => 0],
                ['question' => 'Que signifie CNN ?', 'options' => ['Convolutional Neural Network', 'Computer Neural Network', 'Complex Neural Network', 'Connected Neural Network'], 'correct' => 0],
                ['question' => 'Que signifie RNN ?', 'options' => ['Recurrent Neural Network', 'Random Neural Network', 'Recursive Neural Network', 'Regular Neural Network'], 'correct' => 0],
                ['question' => 'Quel algorithme est utilisé pour la classification ?', 'options' => ['K-means', 'Decision Tree', 'Linear Regression', 'PCA'], 'correct' => 1],
                ['question' => 'Que signifie NLP ?', 'options' => ['Natural Language Processing', 'Neural Learning Process', 'Network Layer Protocol', 'New Learning Pattern'], 'correct' => 0],
                ['question' => 'Quel est l\'objectif du Deep Learning ?', 'options' => ['Apprendre des représentations', 'Stocker des données', 'Créer des sites web', 'Gérer des bases de données'], 'correct' => 0],
                ['question' => 'Qu\'est-ce qu\'un dataset ?', 'options' => ['Un ensemble de données', 'Un algorithme', 'Un réseau', 'Un langage'], 'correct' => 0],
                ['question' => 'Que signifie GPU ?', 'options' => ['Graphics Processing Unit', 'General Processing Unit', 'Global Processing Unit', 'Graphical Program Unit'], 'correct' => 0],
                ['question' => 'Quel est le rôle d\'une fonction d\'activation ?', 'options' => ['Introduire de la non-linéarité', 'Stocker des données', 'Compiler du code', 'Créer des graphiques'], 'correct' => 0],
                ['question' => 'Que signifie overfitting ?', 'options' => ['Surapprentissage', 'Sous-apprentissage', 'Apprentissage optimal', 'Apprentissage rapide'], 'correct' => 0],
                ['question' => 'Quelle technique réduit l\'overfitting ?', 'options' => ['Dropout', 'Augmentation', 'Compilation', 'Optimisation'], 'correct' => 0],
            ],
            'python' => [
                ['question' => 'Qui a créé Python ?', 'options' => ['Guido van Rossum', 'James Gosling', 'Brendan Eich', 'Dennis Ritchie'], 'correct' => 0],
                ['question' => 'En quelle année Python a-t-il été créé ?', 'options' => ['1989', '1991', '1995', '2000'], 'correct' => 1],
                ['question' => 'Comment afficher du texte en Python ?', 'options' => ['print()', 'echo()', 'display()', 'show()'], 'correct' => 0],
                ['question' => 'Comment créer une variable en Python ?', 'options' => ['var x = 5', 'x = 5', 'variable x = 5', 'def x = 5'], 'correct' => 1],
                ['question' => 'Comment créer un commentaire sur une ligne ?', 'options' => ['// commentaire', '# commentaire', '/* commentaire */', '-- commentaire'], 'correct' => 1],
                ['question' => 'Comment créer une liste ?', 'options' => ['list = []', 'list = ()', 'list = {}', 'list = <>'], 'correct' => 0],
                ['question' => 'Comment créer un dictionnaire ?', 'options' => ['dict = []', 'dict = ()', 'dict = {}', 'dict = <>'], 'correct' => 2],
                ['question' => 'Comment créer une fonction ?', 'options' => ['function ma_fonction()', 'def ma_fonction()', 'func ma_fonction()', 'create ma_fonction()'], 'correct' => 1],
                ['question' => 'Quelle méthode ajoute un élément à une liste ?', 'options' => ['add()', 'append()', 'insert()', 'push()'], 'correct' => 1],
                ['question' => 'Comment créer une boucle for ?', 'options' => ['for i in range(5)', 'for (i = 0; i < 5; i++)', 'for i = 0 to 5', 'loop i in 5'], 'correct' => 0],
                ['question' => 'Comment créer une condition if ?', 'options' => ['if x > 5:', 'if (x > 5)', 'if x > 5 then', 'if (x > 5) {'], 'correct' => 0],
                ['question' => 'Quelle fonction retourne la longueur d\'une liste ?', 'options' => ['length()', 'len()', 'size()', 'count()'], 'correct' => 1],
                ['question' => 'Comment importer un module ?', 'options' => ['import module', 'include module', 'require module', 'load module'], 'correct' => 0],
                ['question' => 'Quelle méthode convertit une chaîne en entier ?', 'options' => ['int()', 'toInt()', 'parseInt()', 'integer()'], 'correct' => 0],
                ['question' => 'Comment créer une classe ?', 'options' => ['class MaClasse:', 'create class MaClasse', 'new class MaClasse', 'define class MaClasse'], 'correct' => 0],
                ['question' => 'Quelle méthode lit un fichier ?', 'options' => ['read()', 'open().read()', 'file_read()', 'get_file()'], 'correct' => 1],
                ['question' => 'Comment créer un tuple ?', 'options' => ['tuple = []', 'tuple = ()', 'tuple = {}', 'tuple = <>'], 'correct' => 1],
                ['question' => 'Quelle méthode divise une chaîne ?', 'options' => ['split()', 'divide()', 'separate()', 'cut()'], 'correct' => 0],
                ['question' => 'Comment créer un ensemble (set) ?', 'options' => ['set = []', 'set = ()', 'set = {}', 'set = set()'], 'correct' => 3],
                ['question' => 'Quelle fonction génère un nombre aléatoire ?', 'options' => ['random.random()', 'rand()', 'Math.random()', 'random()'], 'correct' => 0],
            ],
            'java' => [
                ['question' => 'Qui a créé Java ?', 'options' => ['James Gosling', 'Guido van Rossum', 'Brendan Eich', 'Dennis Ritchie'], 'correct' => 0],
                ['question' => 'En quelle année Java a-t-il été créé ?', 'options' => ['1991', '1995', '2000', '2005'], 'correct' => 1],
                ['question' => 'Comment afficher du texte en Java ?', 'options' => ['System.out.println()', 'print()', 'echo()', 'display()'], 'correct' => 0],
                ['question' => 'Comment déclarer une variable en Java ?', 'options' => ['int x = 5', 'var x = 5', 'x = 5', 'variable x = 5'], 'correct' => 0],
                ['question' => 'Comment créer un commentaire sur une ligne ?', 'options' => ['// commentaire', '# commentaire', '/* commentaire */', '-- commentaire'], 'correct' => 0],
                ['question' => 'Comment créer un tableau ?', 'options' => ['int[] arr = new int[5]', 'int arr = []', 'array arr = []', 'int arr = {}'], 'correct' => 0],
                ['question' => 'Comment créer une classe ?', 'options' => ['class MaClasse {}', 'create class MaClasse', 'new class MaClasse', 'define class MaClasse'], 'correct' => 0],
                ['question' => 'Quelle méthode retourne la longueur d\'un tableau ?', 'options' => ['length', 'length()', 'size()', 'count()'], 'correct' => 0],
                ['question' => 'Comment créer une boucle for ?', 'options' => ['for (int i = 0; i < 5; i++)', 'for i in range(5)', 'for i = 0 to 5', 'loop i < 5'], 'correct' => 0],
                ['question' => 'Comment créer une condition if ?', 'options' => ['if (x > 5)', 'if x > 5', 'if (x > 5) then', 'if x > 5 then'], 'correct' => 0],
                ['question' => 'Quelle méthode ajoute un élément à une ArrayList ?', 'options' => ['add()', 'append()', 'insert()', 'push()'], 'correct' => 0],
                ['question' => 'Comment créer une méthode ?', 'options' => ['public void maMethode() {}', 'def maMethode()', 'function maMethode()', 'create maMethode()'], 'correct' => 0],
                ['question' => 'Quel mot-clé définit une constante ?', 'options' => ['const', 'final', 'static', 'constant'], 'correct' => 1],
                ['question' => 'Comment créer un objet ?', 'options' => ['MaClasse obj = new MaClasse()', 'new MaClasse()', 'create MaClasse()', 'MaClasse obj = MaClasse()'], 'correct' => 0],
                ['question' => 'Quelle interface représente une collection ?', 'options' => ['Collection', 'List', 'Set', 'Toutes les réponses'], 'correct' => 3],
                ['question' => 'Comment gérer une exception ?', 'options' => ['try-catch', 'try-except', 'catch-error', 'handle-exception'], 'correct' => 0],
                ['question' => 'Quelle méthode convertit une chaîne en entier ?', 'options' => ['Integer.parseInt()', 'int()', 'toInt()', 'parseInt()'], 'correct' => 0],
                ['question' => 'Comment créer un thread ?', 'options' => ['extends Thread', 'implements Runnable', 'Les deux A et B', 'new Thread()'], 'correct' => 2],
                ['question' => 'Quelle méthode lit un fichier ?', 'options' => ['FileReader', 'BufferedReader', 'Scanner', 'Toutes les réponses'], 'correct' => 3],
                ['question' => 'Quelle annotation marque une méthode de test ?', 'options' => ['@Test', '@TestAnnotation', '@TestMethod', '@TestFunction'], 'correct' => 0],
            ],
            'sql' => [
                ['question' => 'Que signifie SQL ?', 'options' => ['Structured Query Language', 'Simple Query Language', 'Standard Query Language', 'System Query Language'], 'correct' => 0],
                ['question' => 'Quelle commande sélectionne des données ?', 'options' => ['SELECT', 'GET', 'FETCH', 'RETRIEVE'], 'correct' => 0],
                ['question' => 'Quelle clause filtre les résultats ?', 'options' => ['WHERE', 'FILTER', 'CONDITION', 'IF'], 'correct' => 0],
                ['question' => 'Quelle clause trie les résultats ?', 'options' => ['ORDER BY', 'SORT BY', 'ORDER', 'SORT'], 'correct' => 0],
                ['question' => 'Quelle fonction compte les lignes ?', 'options' => ['COUNT()', 'SUM()', 'TOTAL()', 'NUMBER()'], 'correct' => 0],
                ['question' => 'Quelle fonction calcule la moyenne ?', 'options' => ['AVG()', 'MEAN()', 'AVERAGE()', 'MEDIAN()'], 'correct' => 0],
                ['question' => 'Quelle fonction trouve la valeur maximale ?', 'options' => ['MAX()', 'HIGHEST()', 'TOP()', 'BIGGEST()'], 'correct' => 0],
                ['question' => 'Quelle fonction trouve la valeur minimale ?', 'options' => ['MIN()', 'LOWEST()', 'BOTTOM()', 'SMALLEST()'], 'correct' => 0],
                ['question' => 'Quelle clause groupe les résultats ?', 'options' => ['GROUP BY', 'GROUP', 'CLUSTER BY', 'AGGREGATE BY'], 'correct' => 0],
                ['question' => 'Quel type de JOIN retourne toutes les lignes des deux tables ?', 'options' => ['INNER JOIN', 'LEFT JOIN', 'FULL OUTER JOIN', 'RIGHT JOIN'], 'correct' => 2],
                ['question' => 'Quelle commande insère des données ?', 'options' => ['INSERT', 'ADD', 'CREATE', 'NEW'], 'correct' => 0],
                ['question' => 'Quelle commande modifie des données ?', 'options' => ['UPDATE', 'MODIFY', 'CHANGE', 'EDIT'], 'correct' => 0],
                ['question' => 'Quelle commande supprime des données ?', 'options' => ['DELETE', 'REMOVE', 'DROP', 'CLEAR'], 'correct' => 0],
                ['question' => 'Quelle commande crée une table ?', 'options' => ['CREATE TABLE', 'NEW TABLE', 'MAKE TABLE', 'BUILD TABLE'], 'correct' => 0],
                ['question' => 'Quelle contrainte garantit l\'unicité ?', 'options' => ['UNIQUE', 'DISTINCT', 'ONLY', 'SINGLE'], 'correct' => 0],
                ['question' => 'Quelle contrainte garantit qu\'une valeur n\'est pas NULL ?', 'options' => ['NOT NULL', 'REQUIRED', 'MANDATORY', 'OBLIGATORY'], 'correct' => 0],
                ['question' => 'Quelle clé identifie de manière unique une ligne ?', 'options' => ['PRIMARY KEY', 'UNIQUE KEY', 'FOREIGN KEY', 'INDEX KEY'], 'correct' => 0],
                ['question' => 'Quelle clause limite le nombre de résultats ?', 'options' => ['LIMIT', 'TOP', 'FIRST', 'RESTRICT'], 'correct' => 0],
                ['question' => 'Quel opérateur recherche un motif ?', 'options' => ['LIKE', 'MATCH', 'FIND', 'SEARCH'], 'correct' => 0],
                ['question' => 'Quelle commande crée un index ?', 'options' => ['CREATE INDEX', 'NEW INDEX', 'MAKE INDEX', 'BUILD INDEX'], 'correct' => 0],
            ],
            'c' => [
                ['question' => 'Qui a créé le langage C ?', 'options' => ['Dennis Ritchie', 'James Gosling', 'Guido van Rossum', 'Bjarne Stroustrup'], 'correct' => 0],
                ['question' => 'En quelle année le langage C a-t-il été créé ?', 'options' => ['1969', '1972', '1975', '1980'], 'correct' => 1],
                ['question' => 'Comment afficher du texte en C ?', 'options' => ['printf()', 'print()', 'echo()', 'display()'], 'correct' => 0],
                ['question' => 'Comment déclarer une variable en C ?', 'options' => ['int x = 5', 'var x = 5', 'x = 5', 'variable x = 5'], 'correct' => 0],
                ['question' => 'Comment créer un commentaire sur une ligne ?', 'options' => ['// commentaire', '# commentaire', '/* commentaire */', '-- commentaire'], 'correct' => 0],
                ['question' => 'Comment créer un tableau ?', 'options' => ['int arr[5]', 'int[] arr = new int[5]', 'array arr = []', 'int arr = {}'], 'correct' => 0],
                ['question' => 'Comment créer une fonction ?', 'options' => ['int maFonction() {}', 'def maFonction()', 'function maFonction()', 'create maFonction()'], 'correct' => 0],
                ['question' => 'Quelle fonction retourne la longueur d\'une chaîne ?', 'options' => ['strlen()', 'length()', 'size()', 'count()'], 'correct' => 0],
                ['question' => 'Comment créer une boucle for ?', 'options' => ['for (int i = 0; i < 5; i++)', 'for i in range(5)', 'for i = 0 to 5', 'loop i < 5'], 'correct' => 0],
                ['question' => 'Comment créer une condition if ?', 'options' => ['if (x > 5)', 'if x > 5', 'if (x > 5) then', 'if x > 5 then'], 'correct' => 0],
                ['question' => 'Comment déclarer un pointeur ?', 'options' => ['int *ptr', 'int ptr*', 'pointer int ptr', 'int &ptr'], 'correct' => 0],
                ['question' => 'Comment allouer de la mémoire dynamiquement ?', 'options' => ['malloc()', 'alloc()', 'new()', 'create()'], 'correct' => 0],
                ['question' => 'Comment libérer la mémoire allouée ?', 'options' => ['free()', 'delete()', 'release()', 'remove()'], 'correct' => 0],
                ['question' => 'Comment créer une structure ?', 'options' => ['struct MaStruct {}', 'create struct MaStruct', 'new struct MaStruct', 'define struct MaStruct'], 'correct' => 0],
                ['question' => 'Quelle fonction ouvre un fichier ?', 'options' => ['fopen()', 'open()', 'file_open()', 'open_file()'], 'correct' => 0],
                ['question' => 'Quelle fonction lit un fichier ?', 'options' => ['fread()', 'read()', 'file_read()', 'get_file()'], 'correct' => 0],
                ['question' => 'Quelle fonction écrit dans un fichier ?', 'options' => ['fwrite()', 'write()', 'file_write()', 'put_file()'], 'correct' => 0],
                ['question' => 'Quelle fonction ferme un fichier ?', 'options' => ['fclose()', 'close()', 'file_close()', 'end_file()'], 'correct' => 0],
                ['question' => 'Comment copier une chaîne ?', 'options' => ['strcpy()', 'copy()', 'string_copy()', 'str_dup()'], 'correct' => 0],
                ['question' => 'Comment concaténer deux chaînes ?', 'options' => ['strcat()', 'concat()', 'string_concat()', 'str_join()'], 'correct' => 0],
            ],
            'cpp' => [
                ['question' => 'Qui a créé C++ ?', 'options' => ['Dennis Ritchie', 'Bjarne Stroustrup', 'James Gosling', 'Guido van Rossum'], 'correct' => 1],
                ['question' => 'En quelle année C++ a-t-il été créé ?', 'options' => ['1972', '1983', '1990', '1995'], 'correct' => 1],
                ['question' => 'Comment afficher du texte en C++ ?', 'options' => ['cout <<', 'print()', 'printf()', 'echo'], 'correct' => 0],
                ['question' => 'Comment déclarer une variable en C++ ?', 'options' => ['int x = 5', 'var x = 5', 'x = 5', 'variable x = 5'], 'correct' => 0],
                ['question' => 'Comment créer une classe ?', 'options' => ['class MaClasse {}', 'create class MaClasse', 'new class MaClasse', 'define class MaClasse'], 'correct' => 0],
                ['question' => 'Comment créer un objet ?', 'options' => ['MaClasse obj;', 'obj = new MaClasse()', 'obj = MaClasse()', 'create obj MaClasse'], 'correct' => 0],
                ['question' => 'Comment utiliser l\'héritage ?', 'options' => ['class Enfant : public Parent', 'class Enfant extends Parent', 'class Enfant inherits Parent', 'class Enfant : Parent'], 'correct' => 0],
                ['question' => 'Qu\'est-ce qu\'un template ?', 'options' => ['Une fonction générique', 'Une classe générique', 'Les deux A et B', 'Un fichier modèle'], 'correct' => 2],
                ['question' => 'Comment utiliser un vector ?', 'options' => ['vector<int> v;', 'vector v = []', 'int[] v', 'array v'], 'correct' => 0],
                ['question' => 'Comment allouer de la mémoire en C++ ?', 'options' => ['new', 'malloc()', 'alloc()', 'Les deux A et B'], 'correct' => 3],
                ['question' => 'Comment libérer la mémoire allouée avec new ?', 'options' => ['delete', 'free()', 'release()', 'remove()'], 'correct' => 0],
                ['question' => 'Qu\'est-ce que la STL ?', 'options' => ['Standard Template Library', 'Simple Template Library', 'System Template Library', 'Standard Type Library'], 'correct' => 0],
                ['question' => 'Comment créer un pointeur intelligent ?', 'options' => ['unique_ptr', 'smart_ptr', 'auto_ptr', 'Les deux A et C'], 'correct' => 3],
                ['question' => 'Comment utiliser namespace ?', 'options' => ['using namespace std;', 'namespace std;', 'import std;', 'include std;'], 'correct' => 0],
                ['question' => 'Comment créer une fonction virtuelle ?', 'options' => ['virtual void f()', 'void virtual f()', 'void f() virtual', 'virtual f()'], 'correct' => 0],
                ['question' => 'Comment utiliser auto ?', 'options' => ['auto x = 5;', 'var x = 5;', 'x = auto 5;', 'auto(5)'], 'correct' => 0],
                ['question' => 'Qu\'est-ce qu\'un lambda ?', 'options' => ['Une fonction anonyme', 'Une fonction nommée', 'Une classe', 'Un template'], 'correct' => 0],
                ['question' => 'Comment utiliser range-based for ?', 'options' => ['for (auto x : vec)', 'for x in vec', 'for (x : vec)', 'foreach x in vec'], 'correct' => 0],
                ['question' => 'Comment utiliser std::string ?', 'options' => ['string s = "hello";', 'char* s = "hello";', 'string s("hello");', 'Les deux A et C'], 'correct' => 3],
                ['question' => 'Qu\'est-ce qu\'un constexpr ?', 'options' => ['Une constante calculée à la compilation', 'Une constante calculée à l\'exécution', 'Une variable', 'Une fonction'], 'correct' => 0],
            ],
            'csharp' => [
                ['question' => 'Qui a créé C# ?', 'options' => ['Microsoft', 'Google', 'Oracle', 'Apple'], 'correct' => 0],
                ['question' => 'En quelle année C# a-t-il été créé ?', 'options' => ['1995', '2000', '2005', '2010'], 'correct' => 1],
                ['question' => 'Comment afficher du texte en C# ?', 'options' => ['Console.WriteLine()', 'print()', 'printf()', 'echo'], 'correct' => 0],
                ['question' => 'Comment déclarer une variable en C# ?', 'options' => ['int x = 5', 'var x = 5', 'Les deux A et B', 'x = 5'], 'correct' => 2],
                ['question' => 'Comment créer une classe ?', 'options' => ['class MaClasse {}', 'create class MaClasse', 'new class MaClasse', 'define class MaClasse'], 'correct' => 0],
                ['question' => 'Comment créer un objet ?', 'options' => ['MaClasse obj = new MaClasse();', 'obj = new MaClasse()', 'obj = MaClasse()', 'create obj MaClasse'], 'correct' => 0],
                ['question' => 'Comment utiliser l\'héritage ?', 'options' => ['class Enfant : Parent', 'class Enfant extends Parent', 'class Enfant inherits Parent', 'class Enfant : public Parent'], 'correct' => 0],
                ['question' => 'Qu\'est-ce que LINQ ?', 'options' => ['Language Integrated Query', 'Language Internal Query', 'Library Integrated Query', 'Language Input Query'], 'correct' => 0],
                ['question' => 'Comment utiliser async/await ?', 'options' => ['async Task f() { await ... }', 'async void f() { await ... }', 'async Task f() { wait ... }', 'Les deux A et B'], 'correct' => 3],
                ['question' => 'Comment créer une liste ?', 'options' => ['List<int> list = new List<int>();', 'list = []', 'int[] list', 'array list'], 'correct' => 0],
                ['question' => 'Comment créer un dictionnaire ?', 'options' => ['Dictionary<string, int>', 'dict = {}', 'map<string, int>', 'hash<string, int>'], 'correct' => 0],
                ['question' => 'Qu\'est-ce qu\'une interface ?', 'options' => ['Un contrat que les classes doivent implémenter', 'Une classe abstraite', 'Une méthode', 'Un namespace'], 'correct' => 0],
                ['question' => 'Comment utiliser using ?', 'options' => ['using System;', 'import System;', 'include System;', 'namespace System;'], 'correct' => 0],
                ['question' => 'Comment créer une propriété ?', 'options' => ['public int Age { get; set; }', 'int age;', 'property int Age;', 'var Age;'], 'correct' => 0],
                ['question' => 'Comment utiliser var ?', 'options' => ['var x = 5;', 'var int x = 5;', 'x = var 5;', 'var(5)'], 'correct' => 0],
                ['question' => 'Qu\'est-ce qu\'un délégué ?', 'options' => ['Un type qui représente une référence à une méthode', 'Une classe', 'Une interface', 'Un namespace'], 'correct' => 0],
                ['question' => 'Comment utiliser try/catch ?', 'options' => ['try { } catch { }', 'try { } catch (Exception e) { }', 'try { } finally { }', 'Toutes les réponses'], 'correct' => 3],
                ['question' => 'Comment utiliser foreach ?', 'options' => ['foreach (var item in list)', 'for item in list', 'for (item : list)', 'foreach item in list'], 'correct' => 0],
                ['question' => 'Qu\'est-ce que .NET ?', 'options' => ['Une plateforme de développement', 'Un langage', 'Un framework', 'Les deux A et C'], 'correct' => 3],
                ['question' => 'Comment utiliser string interpolation ?', 'options' => ['$"Hello {name}"', '"Hello " + name', 'string.Format("Hello {0}", name)', 'Les deux A et C'], 'correct' => 3],
            ],
            'dart' => [
                ['question' => 'Qui a créé Dart ?', 'options' => ['Google', 'Microsoft', 'Oracle', 'Facebook'], 'correct' => 0],
                ['question' => 'En quelle année Dart a-t-il été créé ?', 'options' => ['2008', '2011', '2015', '2017'], 'correct' => 1],
                ['question' => 'Comment afficher du texte en Dart ?', 'options' => ['print()', 'console.log()', 'printf()', 'echo'], 'correct' => 0],
                ['question' => 'Comment déclarer une variable en Dart ?', 'options' => ['int x = 5', 'var x = 5', 'Les deux A et B', 'x = 5'], 'correct' => 2],
                ['question' => 'Comment créer une classe ?', 'options' => ['class MaClasse {}', 'create class MaClasse', 'new class MaClasse', 'define class MaClasse'], 'correct' => 0],
                ['question' => 'Comment créer un objet ?', 'options' => ['MaClasse obj = MaClasse();', 'obj = new MaClasse()', 'obj = MaClasse()', 'create obj MaClasse'], 'correct' => 0],
                ['question' => 'Qu\'est-ce qu\'un mixin ?', 'options' => ['Un moyen de réutiliser du code dans plusieurs classes', 'Une classe', 'Une interface', 'Une fonction'], 'correct' => 0],
                ['question' => 'Comment utiliser un Future ?', 'options' => ['Future<String>', 'Promise<String>', 'async String', 'String async'], 'correct' => 0],
                ['question' => 'Comment utiliser async/await ?', 'options' => ['Future<void> f() async { await ... }', 'async void f() { await ... }', 'async f() { wait ... }', 'Future f() async { wait ... }'], 'correct' => 0],
                ['question' => 'Comment créer une liste ?', 'options' => ['List<int> list = [];', 'list = []', 'int[] list', 'array list'], 'correct' => 0],
                ['question' => 'Comment créer un Map ?', 'options' => ['Map<String, int>', 'map = {}', 'dict = {}', 'hash = {}'], 'correct' => 0],
                ['question' => 'Comment utiliser string interpolation ?', 'options' => ['"Hello $name"', '"Hello " + name', 'string.format("Hello {0}", name)', 'Les deux A et B'], 'correct' => 3],
                ['question' => 'Qu\'est-ce que Flutter ?', 'options' => ['Un framework UI pour créer des applications multiplateformes', 'Un langage', 'Une bibliothèque', 'Un IDE'], 'correct' => 0],
                ['question' => 'Comment créer un Widget en Flutter ?', 'options' => ['class MonWidget extends StatelessWidget', 'widget MonWidget', 'create widget MonWidget', 'define widget MonWidget'], 'correct' => 0],
                ['question' => 'Comment utiliser setState ?', 'options' => ['setState(() { })', 'state.set()', 'updateState()', 'changeState()'], 'correct' => 0],
                ['question' => 'Comment utiliser un Stream ?', 'options' => ['Stream<int>', 'stream<int>', 'async int', 'int stream'], 'correct' => 0],
                ['question' => 'Comment utiliser forEach sur une liste ?', 'options' => ['list.forEach((item) { })', 'for item in list', 'for (item : list)', 'foreach item in list'], 'correct' => 0],
                ['question' => 'Comment utiliser where sur une liste ?', 'options' => ['list.where((x) => x > 5)', 'list.filter((x) => x > 5)', 'list.select((x) => x > 5)', 'list.find((x) => x > 5)'], 'correct' => 0],
                ['question' => 'Comment utiliser map sur une liste ?', 'options' => ['list.map((x) => x * 2)', 'list.transform((x) => x * 2)', 'list.apply((x) => x * 2)', 'list.change((x) => x * 2)'], 'correct' => 0],
                ['question' => 'Qu\'est-ce qu\'un const en Dart ?', 'options' => ['Une constante calculée à la compilation', 'Une constante calculée à l\'exécution', 'Une variable', 'Une fonction'], 'correct' => 0],
            ],
            'go' => [
                ['question' => 'Qui a créé Go ?', 'options' => ['Google', 'Microsoft', 'Oracle', 'Facebook'], 'correct' => 0],
                ['question' => 'En quelle année Go a-t-il été créé ?', 'options' => ['2007', '2009', '2012', '2015'], 'correct' => 1],
                ['question' => 'Comment afficher du texte en Go ?', 'options' => ['fmt.Println()', 'print()', 'printf()', 'echo'], 'correct' => 0],
                ['question' => 'Comment déclarer une variable en Go ?', 'options' => ['var x int = 5', 'x := 5', 'Les deux A et B', 'int x = 5'], 'correct' => 2],
                ['question' => 'Comment créer une fonction ?', 'options' => ['func maFonction() {}', 'function maFonction()', 'def maFonction()', 'create maFonction()'], 'correct' => 0],
                ['question' => 'Comment créer une struct ?', 'options' => ['type MaStruct struct {}', 'struct MaStruct {}', 'create struct MaStruct', 'define struct MaStruct'], 'correct' => 0],
                ['question' => 'Qu\'est-ce qu\'une goroutine ?', 'options' => ['Un thread léger', 'Une fonction', 'Une classe', 'Un package'], 'correct' => 0],
                ['question' => 'Comment créer une goroutine ?', 'options' => ['go maFonction()', 'goroutine maFonction()', 'async maFonction()', 'thread maFonction()'], 'correct' => 0],
                ['question' => 'Comment créer un channel ?', 'options' => ['ch := make(chan int)', 'ch = new channel(int)', 'ch = channel(int)', 'ch := channel(int)'], 'correct' => 0],
                ['question' => 'Comment créer une slice ?', 'options' => ['s := []int{}', 's = []', 'int[] s', 'array s'], 'correct' => 0],
                ['question' => 'Comment créer un map ?', 'options' => ['m := make(map[string]int)', 'm = {}', 'map m = {}', 'dict m = {}'], 'correct' => 0],
                ['question' => 'Comment gérer les erreurs en Go ?', 'options' => ['if err != nil', 'try/catch', 'throw/catch', 'error handling'], 'correct' => 0],
                ['question' => 'Comment utiliser defer ?', 'options' => ['defer f()', 'finally f()', 'defer { f() }', 'end f()'], 'correct' => 0],
                ['question' => 'Qu\'est-ce qu\'un package en Go ?', 'options' => ['Un moyen d\'organiser le code', 'Une bibliothèque', 'Un module', 'Les deux A et B'], 'correct' => 3],
                ['question' => 'Comment importer un package ?', 'options' => ['import "fmt"', 'import fmt', 'include "fmt"', 'require "fmt"'], 'correct' => 0],
                ['question' => 'Comment utiliser range ?', 'options' => ['for i, v := range slice', 'for i in slice', 'for (i : slice)', 'foreach i in slice'], 'correct' => 0],
                ['question' => 'Comment utiliser interface ?', 'options' => ['type MaInterface interface {}', 'interface MaInterface {}', 'create interface MaInterface', 'define interface MaInterface'], 'correct' => 0],
                ['question' => 'Comment utiliser switch ?', 'options' => ['switch x { case 1: }', 'switch (x) { case 1: }', 'switch x case 1', 'switch x then 1'], 'correct' => 0],
                ['question' => 'Qu\'est-ce qu\'un pointer en Go ?', 'options' => ['Une référence à une variable', 'Une variable', 'Une fonction', 'Un type'], 'correct' => 0],
                ['question' => 'Comment créer un pointer ?', 'options' => ['p := &x', 'p = *x', 'p = pointer(x)', 'p := new(x)'], 'correct' => 0],
            ],
            'rust' => [
                ['question' => 'Qui a créé Rust ?', 'options' => ['Mozilla', 'Google', 'Microsoft', 'Facebook'], 'correct' => 0],
                ['question' => 'En quelle année Rust a-t-il été créé ?', 'options' => ['2006', '2010', '2012', '2015'], 'correct' => 1],
                ['question' => 'Comment afficher du texte en Rust ?', 'options' => ['println!()', 'print()', 'printf()', 'echo'], 'correct' => 0],
                ['question' => 'Comment déclarer une variable en Rust ?', 'options' => ['let x = 5', 'let mut x = 5', 'Les deux A et B', 'int x = 5'], 'correct' => 2],
                ['question' => 'Qu\'est-ce que l\'ownership ?', 'options' => ['Un système de propriété de la mémoire', 'Une fonction', 'Une classe', 'Un type'], 'correct' => 0],
                ['question' => 'Comment utiliser borrow ?', 'options' => ['&x', '*x', 'borrow x', 'ref x'], 'correct' => 0],
                ['question' => 'Comment créer une struct ?', 'options' => ['struct MaStruct {}', 'type MaStruct struct {}', 'create struct MaStruct', 'define struct MaStruct'], 'correct' => 0],
                ['question' => 'Comment créer un enum ?', 'options' => ['enum MonEnum {}', 'type MonEnum enum {}', 'create enum MonEnum', 'define enum MonEnum'], 'correct' => 0],
                ['question' => 'Comment utiliser match ?', 'options' => ['match x { case => }', 'match x { pattern => }', 'switch x { case }', 'match x then'], 'correct' => 1],
                ['question' => 'Comment gérer les erreurs en Rust ?', 'options' => ['Result<T, E>', 'Option<T>', 'Les deux A et B', 'try/catch'], 'correct' => 2],
                ['question' => 'Comment utiliser Option ?', 'options' => ['Option<T>', 'Optional<T>', 'Maybe<T>', 'Nullable<T>'], 'correct' => 0],
                ['question' => 'Comment utiliser Result ?', 'options' => ['Result<T, E>', 'Result<T>', 'Error<T>', 'Try<T>'], 'correct' => 0],
                ['question' => 'Qu\'est-ce qu\'un trait ?', 'options' => ['Un contrat que les types doivent implémenter', 'Une classe', 'Une interface', 'Les deux A et C'], 'correct' => 3],
                ['question' => 'Comment utiliser impl ?', 'options' => ['impl Trait for Type', 'impl Type for Trait', 'implement Trait Type', 'impl Type Trait'], 'correct' => 0],
                ['question' => 'Comment utiliser Vec ?', 'options' => ['Vec<T>', 'vec<T>', 'vector<T>', 'array<T>'], 'correct' => 0],
                ['question' => 'Comment utiliser HashMap ?', 'options' => ['HashMap<K, V>', 'hash_map<K, V>', 'map<K, V>', 'dict<K, V>'], 'correct' => 0],
                ['question' => 'Qu\'est-ce qu\'un lifetime ?', 'options' => ['La durée de vie d\'une référence', 'Une fonction', 'Une variable', 'Un type'], 'correct' => 0],
                ['question' => 'Comment utiliser \'a ?', 'options' => ['fn f<\'a>(x: &\'a str)', 'fn f(x: \'a str)', 'fn f(x: str<\'a>)', 'fn<\'a> f(x: str)'], 'correct' => 0],
                ['question' => 'Comment utiliser String et &str ?', 'options' => ['String est possédé, &str est une référence', 'Les deux sont identiques', 'String est une référence', '&str est possédé'], 'correct' => 0],
                ['question' => 'Comment utiliser unwrap ?', 'options' => ['x.unwrap()', 'unwrap(x)', 'x.unwrap_or()', 'Les deux A et C'], 'correct' => 3],
            ],
            'ruby' => [
                ['question' => 'Qui a créé Ruby ?', 'options' => ['Yukihiro Matsumoto', 'Guido van Rossum', 'James Gosling', 'Bjarne Stroustrup'], 'correct' => 0],
                ['question' => 'En quelle année Ruby a-t-il été créé ?', 'options' => ['1993', '1995', '2000', '2005'], 'correct' => 1],
                ['question' => 'Comment afficher du texte en Ruby ?', 'options' => ['puts', 'print', 'Les deux A et B', 'echo'], 'correct' => 2],
                ['question' => 'Comment déclarer une variable en Ruby ?', 'options' => ['x = 5', 'var x = 5', 'int x = 5', 'x := 5'], 'correct' => 0],
                ['question' => 'Comment créer une méthode ?', 'options' => ['def maMethode', 'function maMethode', 'method maMethode', 'create maMethode'], 'correct' => 0],
                ['question' => 'Comment créer une classe ?', 'options' => ['class MaClasse', 'class MaClasse {}', 'create class MaClasse', 'define class MaClasse'], 'correct' => 0],
                ['question' => 'Comment créer un objet ?', 'options' => ['obj = MaClasse.new', 'obj = new MaClasse()', 'obj = MaClasse()', 'obj = create MaClasse'], 'correct' => 0],
                ['question' => 'Qu\'est-ce qu\'un module ?', 'options' => ['Un moyen de regrouper des méthodes', 'Une classe', 'Une interface', 'Les deux A et B'], 'correct' => 3],
                ['question' => 'Comment utiliser include ?', 'options' => ['include MonModule', 'import MonModule', 'require MonModule', 'use MonModule'], 'correct' => 0],
                ['question' => 'Comment créer un array ?', 'options' => ['arr = []', 'arr = Array.new', 'Les deux A et B', 'array arr'], 'correct' => 2],
                ['question' => 'Comment créer un hash ?', 'options' => ['h = {}', 'h = Hash.new', 'Les deux A et B', 'dict h'], 'correct' => 2],
                ['question' => 'Comment utiliser each ?', 'options' => ['arr.each { |x| }', 'for x in arr', 'foreach x in arr', 'Les deux A et B'], 'correct' => 3],
                ['question' => 'Comment utiliser map ?', 'options' => ['arr.map { |x| x * 2 }', 'arr.collect { |x| x * 2 }', 'Les deux A et B', 'arr.transform { |x| }'], 'correct' => 2],
                ['question' => 'Comment utiliser select ?', 'options' => ['arr.select { |x| x > 5 }', 'arr.filter { |x| x > 5 }', 'arr.where { |x| }', 'Les deux A et B'], 'correct' => 3],
                ['question' => 'Qu\'est-ce que Ruby on Rails ?', 'options' => ['Un framework web', 'Un langage', 'Une bibliothèque', 'Les deux A et C'], 'correct' => 3],
                ['question' => 'Comment créer un contrôleur Rails ?', 'options' => ['rails generate controller Nom', 'rails create controller Nom', 'rails new controller Nom', 'rails make controller Nom'], 'correct' => 0],
                ['question' => 'Comment créer un modèle Rails ?', 'options' => ['rails generate model Nom', 'rails create model Nom', 'rails new model Nom', 'rails make model Nom'], 'correct' => 0],
                ['question' => 'Qu\'est-ce qu\'une gem ?', 'options' => ['Une bibliothèque Ruby', 'Un package', 'Un module', 'Les deux A et B'], 'correct' => 3],
                ['question' => 'Comment utiliser une gem ?', 'options' => ['gem install nom', 'require "nom"', 'Les deux A et B', 'import nom'], 'correct' => 2],
                ['question' => 'Comment utiliser symbol ?', 'options' => [':sym', 'sym:', ':symbol', 'symbol:'], 'correct' => 0],
            ],
            'cybersecurite' => [
                ['question' => 'Que signifie la triade CIA en cybersécurité ?', 'options' => ['Confidentialité, Intégrité, Disponibilité', 'Central Intelligence Agency', 'Computer Information Access', 'Cybersecurity Information Analysis'], 'correct' => 0],
                ['question' => 'Qu\'est-ce qu\'un malware ?', 'options' => ['Un logiciel malveillant', 'Un antivirus', 'Un pare-feu', 'Un protocole de sécurité'], 'correct' => 0],
                ['question' => 'Qu\'est-ce que le phishing ?', 'options' => ['Une attaque d\'ingénierie sociale', 'Un type de virus', 'Un protocole réseau', 'Un algorithme de chiffrement'], 'correct' => 0],
                ['question' => 'Qu\'est-ce qu\'un firewall ?', 'options' => ['Un système de filtrage du trafic réseau', 'Un antivirus', 'Un système de détection d\'intrusion', 'Un protocole de chiffrement'], 'correct' => 0],
                ['question' => 'Que signifie VPN ?', 'options' => ['Virtual Private Network', 'Very Private Network', 'Virtual Public Network', 'Verified Private Network'], 'correct' => 0],
                ['question' => 'Qu\'est-ce que le chiffrement ?', 'options' => ['La transformation de données en format illisible', 'La suppression de données', 'La copie de données', 'La compression de données'], 'correct' => 0],
                ['question' => 'Qu\'est-ce qu\'une vulnérabilité Zero-Day ?', 'options' => ['Une vulnérabilité inconnue et non corrigée', 'Une vulnérabilité corrigée', 'Un type de malware', 'Un protocole de sécurité'], 'correct' => 0],
                ['question' => 'Qu\'est-ce que l\'authentification à deux facteurs (2FA) ?', 'options' => ['Une méthode de vérification en deux étapes', 'Un type de chiffrement', 'Un protocole réseau', 'Un système de détection'], 'correct' => 0],
                ['question' => 'Qu\'est-ce qu\'une attaque DDoS ?', 'options' => ['Déni de service distribué', 'Data Distribution Service', 'Digital Defense System', 'Dynamic Data Storage'], 'correct' => 0],
                ['question' => 'Qu\'est-ce que le RGPD ?', 'options' => ['Règlement Général sur la Protection des Données', 'Réseau Général de Protection des Données', 'Règlement Général de Prévention des Données', 'Réseau Général de Prévention des Données'], 'correct' => 0],
                ['question' => 'Qu\'est-ce qu\'un IDS ?', 'options' => ['Intrusion Detection System', 'Internet Defense System', 'Internal Data Security', 'Information Defense System'], 'correct' => 0],
                ['question' => 'Qu\'est-ce que le hacking éthique ?', 'options' => ['Le piratage autorisé pour tester la sécurité', 'Le piratage illégal', 'Un type de malware', 'Un protocole de sécurité'], 'correct' => 0],
                ['question' => 'Qu\'est-ce que la cryptographie asymétrique ?', 'options' => ['Un système utilisant une paire de clés (publique/privée)', 'Un système utilisant une seule clé', 'Un type de malware', 'Un protocole réseau'], 'correct' => 0],
                ['question' => 'Qu\'est-ce qu\'un certificat SSL/TLS ?', 'options' => ['Un certificat numérique pour sécuriser les communications', 'Un type de malware', 'Un protocole réseau', 'Un système de détection'], 'correct' => 0],
                ['question' => 'Qu\'est-ce que la gestion des incidents de sécurité ?', 'options' => ['Le processus de réponse aux incidents', 'La prévention des incidents', 'Le chiffrement des données', 'La sauvegarde des données'], 'correct' => 0],
                ['question' => 'Qu\'est-ce que DevSecOps ?', 'options' => ['L\'intégration de la sécurité dans DevOps', 'Un type de malware', 'Un protocole réseau', 'Un système de détection'], 'correct' => 0],
                ['question' => 'Qu\'est-ce que la forensique numérique ?', 'options' => ['L\'investigation d\'incidents de sécurité', 'La prévention des attaques', 'Le chiffrement des données', 'La sauvegarde des données'], 'correct' => 0],
                ['question' => 'Qu\'est-ce qu\'un honeypot ?', 'options' => ['Un système piège pour attirer les attaquants', 'Un type de malware', 'Un protocole réseau', 'Un système de détection'], 'correct' => 0],
                ['question' => 'Qu\'est-ce que la sécurité du cloud ?', 'options' => ['La sécurisation des données et services cloud', 'Un type de malware', 'Un protocole réseau', 'Un système de détection'], 'correct' => 0],
                ['question' => 'Qu\'est-ce que la gouvernance de la sécurité ?', 'options' => ['La gestion stratégique de la sécurité', 'La prévention des attaques', 'Le chiffrement des données', 'La sauvegarde des données'], 'correct' => 0],
            ],
            'data-science' => [
                ['question' => 'Que signifie EDA en Data Science ?', 'options' => ['Exploratory Data Analysis', 'External Data Access', 'Extended Data Analysis', 'Exact Data Analysis'], 'correct' => 0],
                ['question' => 'Quelle bibliothèque Python est utilisée pour la manipulation de données ?', 'options' => ['Pandas', 'NumPy', 'Matplotlib', 'Scikit-learn'], 'correct' => 0],
                ['question' => 'Qu\'est-ce que le Machine Learning supervisé ?', 'options' => ['L\'apprentissage avec des données étiquetées', 'L\'apprentissage sans données étiquetées', 'L\'apprentissage par renforcement', 'L\'apprentissage automatique'], 'correct' => 0],
                ['question' => 'Qu\'est-ce que le clustering ?', 'options' => ['Le regroupement de données similaires', 'La classification de données', 'La régression', 'La visualisation'], 'correct' => 0],
                ['question' => 'Quelle bibliothèque Python est utilisée pour le Machine Learning ?', 'options' => ['Scikit-learn', 'Pandas', 'NumPy', 'Matplotlib'], 'correct' => 0],
                ['question' => 'Qu\'est-ce qu\'un DataFrame ?', 'options' => ['Une structure de données tabulaire en Pandas', 'Un type de graphique', 'Un algorithme', 'Un modèle'], 'correct' => 0],
                ['question' => 'Qu\'est-ce que la validation croisée ?', 'options' => ['Une technique d\'évaluation de modèle', 'Un type de clustering', 'Une méthode de visualisation', 'Un algorithme de régression'], 'correct' => 0],
                ['question' => 'Qu\'est-ce que l\'overfitting ?', 'options' => ['Le surapprentissage d\'un modèle', 'Le sous-apprentissage', 'L\'apprentissage optimal', 'L\'apprentissage rapide'], 'correct' => 0],
                ['question' => 'Quelle bibliothèque Python est utilisée pour la visualisation ?', 'options' => ['Matplotlib et Seaborn', 'Pandas', 'NumPy', 'Scikit-learn'], 'correct' => 0],
                ['question' => 'Qu\'est-ce que la régression linéaire ?', 'options' => ['Un modèle prédictif pour les valeurs continues', 'Un modèle de classification', 'Un algorithme de clustering', 'Une méthode de visualisation'], 'correct' => 0],
                ['question' => 'Qu\'est-ce que le NLP ?', 'options' => ['Natural Language Processing', 'Neural Learning Process', 'Network Layer Protocol', 'New Learning Pattern'], 'correct' => 0],
                ['question' => 'Qu\'est-ce qu\'un feature en Machine Learning ?', 'options' => ['Une variable d\'entrée', 'Un résultat', 'Un modèle', 'Un algorithme'], 'correct' => 0],
                ['question' => 'Qu\'est-ce que le Deep Learning ?', 'options' => ['L\'apprentissage avec des réseaux neuronaux profonds', 'L\'apprentissage superficiel', 'L\'apprentissage par renforcement', 'L\'apprentissage automatique'], 'correct' => 0],
                ['question' => 'Quelle bibliothèque est utilisée pour le Deep Learning ?', 'options' => ['TensorFlow et PyTorch', 'Pandas', 'NumPy', 'Scikit-learn'], 'correct' => 0],
                ['question' => 'Qu\'est-ce que la normalisation des données ?', 'options' => ['La mise à l\'échelle des données', 'La suppression des données', 'La copie des données', 'La compression des données'], 'correct' => 0],
                ['question' => 'Qu\'est-ce qu\'un modèle de classification ?', 'options' => ['Un modèle qui prédit des catégories', 'Un modèle qui prédit des valeurs continues', 'Un algorithme de clustering', 'Une méthode de visualisation'], 'correct' => 0],
                ['question' => 'Qu\'est-ce que la corrélation ?', 'options' => ['La relation entre deux variables', 'La différence entre deux variables', 'La somme de deux variables', 'Le produit de deux variables'], 'correct' => 0],
                ['question' => 'Qu\'est-ce que le feature engineering ?', 'options' => ['La création de nouvelles variables pertinentes', 'La suppression de variables', 'La copie de variables', 'La compression de variables'], 'correct' => 0],
                ['question' => 'Qu\'est-ce qu\'un pipeline de données ?', 'options' => ['Un flux de traitement automatisé des données', 'Un type de graphique', 'Un algorithme', 'Un modèle'], 'correct' => 0],
                ['question' => 'Qu\'est-ce que l\'A/B testing ?', 'options' => ['L\'expérimentation pour comparer deux versions', 'Un type de clustering', 'Une méthode de visualisation', 'Un algorithme de régression'], 'correct' => 0],
            ],
            'big-data' => [
                ['question' => 'Que signifie HDFS ?', 'options' => ['Hadoop Distributed File System', 'High Data File System', 'Huge Data File System', 'Hybrid Data File System'], 'correct' => 0],
                ['question' => 'Qu\'est-ce que MapReduce ?', 'options' => ['Un modèle de programmation pour le traitement distribué', 'Un système de fichiers', 'Un protocole réseau', 'Un algorithme de clustering'], 'correct' => 0],
                ['question' => 'Qu\'est-ce qu\'Apache Spark ?', 'options' => ['Un moteur d\'analyse unifié pour le Big Data', 'Un système de fichiers', 'Un protocole réseau', 'Un algorithme de clustering'], 'correct' => 0],
                ['question' => 'Quels sont les 5 V du Big Data ?', 'options' => ['Volume, Vitesse, Variété, Véracité, Valeur', 'Volume, Vitesse, Variété, Validation, Valeur', 'Volume, Vitesse, Variété, Véracité, Validation', 'Volume, Vitesse, Variété, Véracité, Vérification'], 'correct' => 0],
                ['question' => 'Qu\'est-ce qu\'un Data Lake ?', 'options' => ['Un dépôt de données brutes non structurées', 'Un entrepôt de données structurées', 'Un système de fichiers', 'Un protocole réseau'], 'correct' => 0],
                ['question' => 'Qu\'est-ce qu\'un Data Warehouse ?', 'options' => ['Un entrepôt de données structurées et organisées', 'Un dépôt de données brutes', 'Un système de fichiers', 'Un protocole réseau'], 'correct' => 0],
                ['question' => 'Qu\'est-ce qu\'Apache Kafka ?', 'options' => ['Une plateforme de streaming distribué', 'Un système de fichiers', 'Un protocole réseau', 'Un algorithme de clustering'], 'correct' => 0],
                ['question' => 'Qu\'est-ce que NoSQL ?', 'options' => ['Des bases de données non relationnelles', 'Des bases de données relationnelles', 'Un système de fichiers', 'Un protocole réseau'], 'correct' => 0],
                ['question' => 'Qu\'est-ce qu\'un RDD dans Spark ?', 'options' => ['Resilient Distributed Dataset', 'Real-time Data Distribution', 'Reliable Data Distribution', 'Rapid Data Distribution'], 'correct' => 0],
                ['question' => 'Qu\'est-ce que le streaming de données ?', 'options' => ['Le traitement de données en temps réel', 'Le stockage de données', 'La copie de données', 'La compression de données'], 'correct' => 0],
                ['question' => 'Qu\'est-ce qu\'un NameNode dans HDFS ?', 'options' => ['Le nœud maître qui gère les métadonnées', 'Un nœud de données', 'Un protocole réseau', 'Un algorithme'], 'correct' => 0],
                ['question' => 'Qu\'est-ce qu\'un DataNode dans HDFS ?', 'options' => ['Un nœud qui stocke les données', 'Le nœud maître', 'Un protocole réseau', 'Un algorithme'], 'correct' => 0],
                ['question' => 'Qu\'est-ce que la réplication dans HDFS ?', 'options' => ['La copie de données sur plusieurs nœuds', 'La suppression de données', 'La compression de données', 'Le chiffrement de données'], 'correct' => 0],
                ['question' => 'Qu\'est-ce qu\'un DataFrame dans Spark ?', 'options' => ['Une structure de données distribuée', 'Un système de fichiers', 'Un protocole réseau', 'Un algorithme'], 'correct' => 0],
                ['question' => 'Qu\'est-ce que le batch processing ?', 'options' => ['Le traitement par lots', 'Le traitement en temps réel', 'Le stockage de données', 'La copie de données'], 'correct' => 0],
                ['question' => 'Qu\'est-ce que MongoDB ?', 'options' => ['Une base de données NoSQL orientée documents', 'Une base de données relationnelle', 'Un système de fichiers', 'Un protocole réseau'], 'correct' => 0],
                ['question' => 'Qu\'est-ce que Cassandra ?', 'options' => ['Une base de données NoSQL orientée colonnes', 'Une base de données relationnelle', 'Un système de fichiers', 'Un protocole réseau'], 'correct' => 0],
                ['question' => 'Qu\'est-ce que la scalabilité horizontale ?', 'options' => ['L\'ajout de nœuds pour augmenter la capacité', 'L\'amélioration des nœuds existants', 'La suppression de nœuds', 'Le remplacement de nœuds'], 'correct' => 0],
                ['question' => 'Qu\'est-ce que Spark Streaming ?', 'options' => ['Le traitement de flux de données en temps réel avec Spark', 'Le stockage de données', 'La copie de données', 'La compression de données'], 'correct' => 0],
                ['question' => 'Qu\'est-ce que la gouvernance des données Big Data ?', 'options' => ['La gestion et le contrôle des données', 'Le stockage de données', 'La copie de données', 'La compression de données'], 'correct' => 0],
            ],
            'swift' => [
                ['question' => 'Qui a créé Swift ?', 'options' => ['Apple', 'Google', 'Microsoft', 'Facebook'], 'correct' => 0],
                ['question' => 'En quelle année Swift a-t-il été créé ?', 'options' => ['2010', '2014', '2016', '2018'], 'correct' => 1],
                ['question' => 'Comment afficher du texte en Swift ?', 'options' => ['print()', 'console.log()', 'printf()', 'echo'], 'correct' => 0],
                ['question' => 'Comment déclarer une constante en Swift ?', 'options' => ['let nom = "Swift"', 'const nom = "Swift"', 'var nom = "Swift"', 'constant nom = "Swift"'], 'correct' => 0],
                ['question' => 'Comment déclarer une variable modifiable en Swift ?', 'options' => ['var nom = "Swift"', 'let nom = "Swift"', 'mutable nom = "Swift"', 'variable nom = "Swift"'], 'correct' => 0],
                ['question' => 'Qu\'est-ce qu\'un Optional en Swift ?', 'options' => ['Un type qui peut être nil', 'Un type qui ne peut jamais être nil', 'Un tableau', 'Un dictionnaire'], 'correct' => 0],
                ['question' => 'Comment déballer un Optional avec if let ?', 'options' => ['if let valeur = optional { }', 'if optional != nil { }', 'if optional { }', 'if let optional { }'], 'correct' => 0],
                ['question' => 'Comment créer un tableau en Swift ?', 'options' => ['var arr = [1, 2, 3]', 'var arr = Array(1, 2, 3)', 'var arr = new Array(1, 2, 3)', 'Les deux A et B'], 'correct' => 3],
                ['question' => 'Comment créer un dictionnaire en Swift ?', 'options' => ['var dict = ["key": "value"]', 'var dict = Dictionary()', 'var dict = {}', 'Les deux A et B'], 'correct' => 3],
                ['question' => 'Comment utiliser une boucle for-in ?', 'options' => ['for item in array { }', 'for (item in array) { }', 'for item : array { }', 'foreach item in array { }'], 'correct' => 0],
                ['question' => 'Comment créer une fonction en Swift ?', 'options' => ['func maFonction() { }', 'function maFonction() { }', 'def maFonction() { }', 'create maFonction() { }'], 'correct' => 0],
                ['question' => 'Comment créer une classe en Swift ?', 'options' => ['class MaClasse { }', 'class MaClasse {}', 'create class MaClasse', 'define class MaClasse'], 'correct' => 0],
                ['question' => 'Qu\'est-ce qu\'un protocole en Swift ?', 'options' => ['Un contrat que les types doivent implémenter', 'Une classe', 'Une fonction', 'Un type'], 'correct' => 0],
                ['question' => 'Comment gérer les erreurs en Swift ?', 'options' => ['do-catch', 'try-catch', 'throw-catch', 'error-handling'], 'correct' => 0],
                ['question' => 'Qu\'est-ce que SwiftUI ?', 'options' => ['Un framework pour créer des interfaces utilisateur', 'Un langage', 'Une bibliothèque', 'Un IDE'], 'correct' => 0],
                ['question' => 'Comment utiliser guard let ?', 'options' => ['guard let valeur = optional else { return }', 'guard optional != nil else { return }', 'guard let optional else { return }', 'guard optional else { return }'], 'correct' => 0],
                ['question' => 'Qu\'est-ce qu\'une closure en Swift ?', 'options' => ['Un bloc de code autonome', 'Une fonction nommée', 'Une classe', 'Un type'], 'correct' => 0],
                ['question' => 'Comment utiliser switch en Swift ?', 'options' => ['switch valeur { case 1: }', 'switch (valeur) { case 1: }', 'switch valeur case 1', 'switch valeur then 1'], 'correct' => 0],
                ['question' => 'Qu\'est-ce qu\'une extension en Swift ?', 'options' => ['Un moyen d\'ajouter des fonctionnalités à un type existant', 'Une classe', 'Une fonction', 'Un protocole'], 'correct' => 0],
                ['question' => 'Comment utiliser string interpolation en Swift ?', 'options' => ['"Hello \\(nom)"', '"Hello " + nom', 'string.format("Hello {0}", nom)', 'Les deux A et B'], 'correct' => 0],
            ],
            'perl' => [
                ['question' => 'Qui a créé Perl ?', 'options' => ['Larry Wall', 'Guido van Rossum', 'James Gosling', 'Bjarne Stroustrup'], 'correct' => 0],
                ['question' => 'En quelle année Perl a-t-il été créé ?', 'options' => ['1985', '1987', '1990', '1995'], 'correct' => 1],
                ['question' => 'Comment afficher du texte en Perl ?', 'options' => ['print', 'puts', 'console.log()', 'echo'], 'correct' => 0],
                ['question' => 'Quel sigil utilise-t-on pour les variables scalaires ?', 'options' => ['$', '@', '%', '&'], 'correct' => 0],
                ['question' => 'Quel sigil utilise-t-on pour les tableaux ?', 'options' => ['@', '$', '%', '#'], 'correct' => 0],
                ['question' => 'Quel sigil utilise-t-on pour les hash ?', 'options' => ['%', '$', '@', '&'], 'correct' => 0],
                ['question' => 'Comment déclarer une variable locale en Perl ?', 'options' => ['my $var', 'var $var', 'local $var', 'let $var'], 'correct' => 0],
                ['question' => 'Comment créer un tableau en Perl ?', 'options' => ['my @arr = (1, 2, 3)', 'my @arr = [1, 2, 3]', 'my arr = (1, 2, 3)', 'Les deux A et B'], 'correct' => 0],
                ['question' => 'Comment créer un hash en Perl ?', 'options' => ['my %hash = ("key" => "value")', 'my %hash = {"key": "value"}', 'my hash = {"key": "value"}', 'Les deux A et B'], 'correct' => 0],
                ['question' => 'Comment utiliser une expression régulière en Perl ?', 'options' => ['$texte =~ /pattern/', '$texte =~ pattern', '$texte ~ /pattern/', '$texte match /pattern/'], 'correct' => 0],
                ['question' => 'Comment créer une fonction en Perl ?', 'options' => ['sub maFonction { }', 'function maFonction { }', 'def maFonction { }', 'create maFonction { }'], 'correct' => 0],
                ['question' => 'Qu\'est-ce que CPAN ?', 'options' => ['Comprehensive Perl Archive Network', 'Central Perl Archive Network', 'Common Perl Archive Network', 'Complete Perl Archive Network'], 'correct' => 0],
                ['question' => 'Comment utiliser use strict en Perl ?', 'options' => ['use strict;', 'require strict;', 'import strict;', 'include strict;'], 'correct' => 0],
                ['question' => 'Comment utiliser une boucle for en Perl ?', 'options' => ['for my $i (1..10) { }', 'for ($i = 1; $i <= 10; $i++) { }', 'for i in 1..10 { }', 'Les deux A et B'], 'correct' => 3],
                ['question' => 'Comment accéder au premier élément d\'un tableau ?', 'options' => ['$arr[0]', '$arr[1]', '@arr[0]', 'arr[0]'], 'correct' => 0],
                ['question' => 'Comment accéder à une valeur dans un hash ?', 'options' => ['$hash{key}', '$hash[key]', '$hash->key', 'hash{key}'], 'correct' => 0],
                ['question' => 'Qu\'est-ce qu\'une référence en Perl ?', 'options' => ['Une référence à une variable', 'Une variable', 'Une fonction', 'Un type'], 'correct' => 0],
                ['question' => 'Comment créer une référence à un tableau ?', 'options' => ['my $ref = \\@array', 'my $ref = @array', 'my $ref = *array', 'my $ref = &array'], 'correct' => 0],
                ['question' => 'Comment utiliser un module Perl ?', 'options' => ['use ModuleName;', 'import ModuleName;', 'require ModuleName;', 'include ModuleName;'], 'correct' => 0],
                ['question' => 'Quelle est la devise de Perl ?', 'options' => ['There\'s more than one way to do it', 'Simple is better than complex', 'Write once, run anywhere', 'Perfection is achieved'], 'correct' => 0],
            ],
            'typescript' => [
                ['question' => 'Qui a créé TypeScript ?', 'options' => ['Microsoft', 'Google', 'Facebook', 'Apple'], 'correct' => 0],
                ['question' => 'En quelle année TypeScript a-t-il été créé ?', 'options' => ['2010', '2012', '2014', '2016'], 'correct' => 1],
                ['question' => 'Qu\'est-ce que TypeScript ?', 'options' => ['Un sur-ensemble typé de JavaScript', 'Un nouveau langage', 'Une bibliothèque JavaScript', 'Un framework'], 'correct' => 0],
                ['question' => 'Comment déclarer une variable typée en TypeScript ?', 'options' => ['let nom: string = "TypeScript"', 'let nom = "TypeScript"', 'var nom: string = "TypeScript"', 'Les deux A et C'], 'correct' => 3],
                ['question' => 'Comment créer une interface en TypeScript ?', 'options' => ['interface Personne { }', 'interface Personne {}', 'create interface Personne', 'define interface Personne'], 'correct' => 0],
                ['question' => 'Comment créer une classe en TypeScript ?', 'options' => ['class MaClasse { }', 'class MaClasse {}', 'create class MaClasse', 'define class MaClasse'], 'correct' => 0],
                ['question' => 'Qu\'est-ce qu\'un générique en TypeScript ?', 'options' => ['Un type variable', 'Un type fixe', 'Une fonction', 'Une classe'], 'correct' => 0],
                ['question' => 'Comment utiliser un générique ?', 'options' => ['function f<T>(x: T): T { }', 'function f<T>(x: T) { }', 'function f(x: T): T { }', 'function<T> f(x: T) { }'], 'correct' => 0],
                ['question' => 'Comment créer un enum en TypeScript ?', 'options' => ['enum MonEnum { }', 'enum MonEnum {}', 'create enum MonEnum', 'define enum MonEnum'], 'correct' => 0],
                ['question' => 'Qu\'est-ce qu\'un tuple en TypeScript ?', 'options' => ['Un tableau à taille fixe avec types spécifiques', 'Un tableau normal', 'Un objet', 'Une fonction'], 'correct' => 0],
                ['question' => 'Comment créer un tuple ?', 'options' => ['let t: [string, number] = ["a", 1]', 'let t = ["a", 1]', 'let t: tuple = ["a", 1]', 'let t = tuple("a", 1)'], 'correct' => 0],
                ['question' => 'Qu\'est-ce qu\'une union type ?', 'options' => ['Un type qui accepte plusieurs types', 'Un type unique', 'Un tableau', 'Un objet'], 'correct' => 0],
                ['question' => 'Comment utiliser une union type ?', 'options' => ['let x: string | number', 'let x: string or number', 'let x: string || number', 'let x: string & number'], 'correct' => 0],
                ['question' => 'Qu\'est-ce que Partial<T> ?', 'options' => ['Un utility type qui rend toutes les propriétés optionnelles', 'Un type qui rend toutes les propriétés requises', 'Un type qui sélectionne des propriétés', 'Un type qui exclut des propriétés'], 'correct' => 0],
                ['question' => 'Comment utiliser import/export en TypeScript ?', 'options' => ['export function f() { } puis import { f } from "./file"', 'export f() puis import f', 'Les deux A et B', 'Aucune des réponses'], 'correct' => 0],
                ['question' => 'Qu\'est-ce qu\'un type guard ?', 'options' => ['Une fonction qui rétrécit le type', 'Une fonction qui élargit le type', 'Une fonction qui change le type', 'Une fonction qui supprime le type'], 'correct' => 0],
                ['question' => 'Comment utiliser async/await en TypeScript ?', 'options' => ['async function f() { await ... }', 'async function f() { wait ... }', 'function async f() { await ... }', 'function f() async { await ... }'], 'correct' => 0],
                ['question' => 'Qu\'est-ce qu\'un décorateur en TypeScript ?', 'options' => ['Un moyen d\'ajouter des métadonnées', 'Une fonction', 'Une classe', 'Un type'], 'correct' => 0],
                ['question' => 'Comment utiliser React.FC avec TypeScript ?', 'options' => ['const Component: React.FC<Props> = () => { }', 'const Component: React.FC = () => { }', 'function Component: React.FC() { }', 'Les deux A et B'], 'correct' => 0],
                ['question' => 'Quelle extension de fichier utilise TypeScript ?', 'options' => ['.ts', '.js', '.tsx', 'Les deux A et C'], 'correct' => 3],
            ],
        ];

        return $allQuestions[$language] ?? [];
    }


}